version: 1

build:
  dockerfile: Dockerfile
  context: .

app:
  name: chatbot-automation
  type: web
  framework: nextjs
  env:
    NODE_ENV: production
    NEXT_TELEMETRY_DISABLED: 1

deploy:
  strategy: docker
  replicas: 1
  port: 3000
